homeassistant:
  enabled: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: zoa9VaibookeeGho2BaiWu1eilotaYei5thooleiVeemoh9ja2Dahtheogh8eid1
serial:
  port: /dev/ttyACM0
  adapter: deconz
frontend:
  enabled: true
  port: 8099
devices:
  '0x00158d0001a16e08':
    friendly_name: Bedroom Main Light
  '0x680ae2fffe957376':
    friendly_name: Stairs 1
  '0x680ae2fffe96ed14':
    friendly_name: Stairs 2
  '0x7cb03eaa0a04fe91':
    friendly_name: Living Room Main Light
  '0x00158d0001a1a06d':
    friendly_name: Spare Hive
  '0x7cb03eaa0a0481b5':
    friendly_name: Living Room Lamp
  '0x7cb03eaa0a0458f9':
    friendly_name: Bar
  '0x00158d000452357f':
    friendly_name: Window - Study
  '0x5c0272fffebe2fb6':
    friendly_name: '0x5c0272fffebe2fb6'
    homeassistant:
      name: TRV-Room2
    optimistic: true
  '0xa4c1381fa71fa2af':
    friendly_name: TH_01
  '0xa4c1386591aac905':
    friendly_name: TH_02
  '0xa4c1386ab09b48f2':
    friendly_name: TH_03
  '0xa4c138b556862604':
    friendly_name: M_01
  '0xa4c138f24e1cef1e':
    friendly_name: TH_04
  '0xa4c138fb6e5add12':
    friendly_name: TH_05
  '0xa4c138b346675662':
    friendly_name: TH_06
  '0xa4c1383663e5f7a1':
    friendly_name: M_02
  '0xa4c13843eb1e6c65':
    friendly_name: M_03
  '0xa4c13874bde1fabf':
    friendly_name: Spare Room
  '0xa4c138d082ef7de1':
    friendly_name: Dining
  '0xb40ecfd120a50000':
    friendly_name: Bedside Lamp
  '0xa4c138e31ec0007a':
    friendly_name: '0xa4c138e31ec0007a'
  '0x70b3d52b600930ff':
    friendly_name: Tumble Dryer
  '0x94b216fffe74f1b2':
    friendly_name: v2l
  '0xa4c1385bdd699073':
    friendly_name: Battery Sensor
groups: {}
version: 4
